###  Meeting Date

2025-11-04

### Facilitator

Steve Turoscy

### Meeting Reference / Notes

_No response_

---

### ESGF-NG Load Testing Status

**Scope:**
- Authentication + authorization enabled
- Validation enabled
- Input data: CMIP6 + Obs4MIPs
- Target: ≥12 transactions/min over 48 hours

**Dependencies:**
- [CMIP6 Extension v1.0.0](https://esgf.github.io/stac-transaction-api/cmip6/v1.0.0/schema.json)
- [obsMIPs Extension v1.0.0](https://esgf.github.io/stac-transaction-api/obs4mips/v1.0.0/schema.json)
- [STAC Extensions Repo](https://github.com/ESGF/stac-transaction-api/tree/main/stac-extensions)
- [Transaction API PR #32](https://github.com/ESGF/stac-transaction-api/pull/32)

**Tasks:**
- [ ] Redeploy Transaction API with updated schema refs
- [ ] Run 48-hour load test
- [ ] Collect metrics (throughput, latency, errors)
- [ ] Summarize results

---

### Publisher Integration Testing

Reference: [esgf-roadmap#92](https://github.com/ESGF/esgf-roadmap/issues/92)

**Tasks:**
- [ ] Create test infrastructure for Publisher team (Sasha)
- [ ] Deploy East & West instances for auth testing
- [ ] Provide local Docker setup instructions
- [ ] Validate publisher → STAC end-to-end flow

---

### Schema & Validation Consistency

References:
- [Schema Docs #83](https://github.com/ESGF/esgf-roadmap/issues/83)
- [Checksums #84](https://github.com/ESGF/esgf-roadmap/issues/84)

**Tasks:**
- [ ] Clarify meanings in reference files within assets
- [ ] Verify checksum generation with esgmapfile

---

### Field Conventions & Extensions

Reference: [Field Prefix Convention #82](https://github.com/ESGF/esgf-roadmap/issues/82)

**Tasks:**
- [ ] Document project-specific field prefix conventions
- [ ] Update schemas to enforce prefixes
- [ ] Notify publishers of validation changes
- [ ] Enable free-text extension for West catalog

---

### REF Integration & Data Challenge Coordination

Reference: [REF Integration #93](https://github.com/ESGF/esgf-roadmap/issues/93)

**Tasks:**
- [ ] Reach out to REF members for obs4REF schema validation
- [ ] Onboard REF team members to event stream
- [ ] Execute additional data challenge runs
- [ ] Document REF-published data

---

### Coordination & External Dependencies

**External Partners:**
- [ ] CEDA: Free-text extension verified (East)
- [ ] ESA: STAC/Zarr best-practice doc shared
- [ ] Globus Ops: Production deployment planning
- [ ] CMIP7: Check ESGVOC CVs and announcements

---

### Ongoing Projects & Reminders

- [ ] ESGF Replicator planning — (Steve)
- [ ] PID Service downstream Kafka client (Katharina)

---

### Discussion & Open Questions

_No response_

---

### Next Steps / Assignments

| Task | Owner | Due |
|------|--------|-----|
| Publish STAC schemas | Lukasz | TBD |
| Redeploy Transaction API | Steve | TBD |
| Publisher test infra setup | Sasha/Steve | TBD |

---

### Next Review Date

2025-11-11