name: Create ESGF-NG Agenda Issues
on:
  workflow_dispatch:  # Run manually from GitHub Actions tab

jobs:
  create_issues:
    name: Create ESGF-NG Issues
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ESGF-NG issues from agenda
        uses: peter-evans/create-issue-from-file@v4
        with:
          # Repository where the issues should be created by default
          repository: sturoscy-personal/esgf-roadmap
          content-filepath: .github/workflows/esgf-ng-issues.md
          title: "ESGF-NG Agenda Issue: Batch Creation Placeholder"
          # This placeholder will be ignored; real issues are created below

  matrix_create:
    name: Create Individual ESGF-NG Issues
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - title: "Run 48-hour ESGF-NG Load Test with Auth + Validation Enabled"
            body: |
              Execute 48h load test using CMIP6 + obs4MIPs datasets with authentication 
              and validation enabled. Record throughput, latency, and error rates.
              Target: minimum 12 transactions/min sustained.
            labels: load-test,infrastructure
            repo: sturoscy-personal/esgf-roadmap

          - title: "Publish CMIP6 + obs4MIPs Schemas to GitHub Pages and Redeploy Transaction API"
            body: |
              Publish updated schemas under `/stac-extensions` on GitHub Pages.
              Redeploy Transaction API and verify schema integration.
            labels: schema,docs,release
            repo: sturoscy-personal/esgf-roadmap

          - title: "Create Publisher Integration Testing Infrastructure"
            body: |
              Stand up test environment accessible to publisher team (e.g., Sasha).
              Support both East and West endpoints.
              Reference https://github.com/sturoscy-personal/esgf-roadmap/issues/92.
            labels: publisher,testing,urgent
            repo: sturoscy-personal/esgf-roadmap

          - title: "Add Free-Text Extension Support for West Catalog"
            body: |
              Mirror CEDA’s free-text extension currently supported in the East catalog.
              Validate functionality within the STAC FastAPI implementation.
            labels: feature,metadata
            repo: sturoscy-personal/esgf-roadmap

          - title: "Need clarity for meanings of fields in reference files within assets"
            body: |
              Capture guidance from STAC community on JSON schema design and referencing.
              Reference https://github.com/sturoscy-personal/esgf-roadmap/issues/83.
            labels: schema,docs
            repo: sturoscy-personal/esgf-roadmap

          - title: "Verify Checksums Across East & West Catalogs"
            body: |
              Ensure checksum generation from `esgmapfile` produces consistent hashes.
              Reopen https://github.com/sturoscy-personal/esgf-roadmap/issues/84 if discrepancies reappear.
            labels: validation,bug,sync
            repo: sturoscy-personal/esgf-roadmap

          - title: "ESGF Replicator Planning"
            body: |
              Plan and track development for ESGF Replicator component.
              Document interfaces, data flow, and testing milestones.
            labels: replicator,planning
            repo: sturoscy-personal/esgf-roadmap

    steps:
      - name: Create issues
        uses: peter-evans/create-issue@v5
        with:
          repository: ${{ matrix.repo }}
          title: ${{ matrix.title }}
          body: ${{ matrix.body }}
          labels: ${{ matrix.labels }}

      # - name: Add issue to ESGF-core-architecture project board
      #   uses: github/add-to-project@v1.1.0
      #   with:
      #     project-url: https://github.com/orgs/ESGF/projects/11
      #     item-id: ${{ steps.create_issue.outputs.issue_node_id }}
